version: "3.8"
services:
  strapi:
    build: ./apps/cms
    container_name: strapi
    ports:
      - "20001:20001"
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 20001
    restart: always

  nextjs:
    build: ./apps/web
    container_name: nextjs
    ports:
      - "20002:20002"
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 20002
    restart: always
